{% set name = "youtube-transcript-api" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/youtube_transcript_api-{{ version }}.tar.gz
  sha256: 820977c8402e2e7f8ce86817e05044ddc8c5fe7085cb8058b9a21e14153a27ba

build:
  number: 0
  noarch: python
  entry_points:
    - youtube_transcript_api = youtube_transcript_api.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - requests >=2.24.0

test:
  imports:
    - youtube_transcript_api
    - youtube_transcript_api.test
  commands:
    - pip check
    - youtube_transcript_api --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jdepoix/youtube-transcript-api
  summary: This is an python API which allows you to get the transcripts/subtitles for a given YouTube video. It also works for automatically generated subtitles, supports translating subtitles and it does not require a headless browser, like other selenium based solutions do!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
